name: Deploy to Lightsail

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment artifact
        run: zip -r deploy.zip ./*

      - name: Deploy to Lightsail
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: deploy.zip
          target: /home/ubuntu/meteordatavis
