name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment artifact
        run: zip -r deploy.zip ./*

      - name: Deploy to Lightsail
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: deploy.zip
          target: /home/ubuntu/meteordatavis

      - name: Extract files on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/ubuntu/meteordatavis
            unzip -o deploy.zip
            rm deploy.zip  # Facultatif : supprime l'archive après extraction
